### ISSUE TITLE
I want to purchase an upgrade

### ISSUE THREAD

**Issue by ndow1021** [ndow1021/CS478Project#2]
I have enough bananas collected for an upgrade and I need somewhere to buy and see all of my given upgrades. I need these upgrades to increase my bananas per second and my progress towards achievements

**Comment by Str-Josh** [comment]
As a player, I would like to be able to visit a Bazaar or other location so that I can use my collection of bananas to purchase upgrades that I can then use to increase my progress towards other achievements.
